### ISSUE TITLE
Present KPIs to TT-GISC

### ISSUE THREAD

**Issue by efucile** [wmo-im/wmcp#13]
TT-GISC is going to have a meeting in Offenbach 26-29 August 2019. It is very important that the activity of defining KPIs for the metadata is done in coordination with TT-GISC. We should finalise a first draft and present it at the  meeting with the aim to decide how TT-GISC will act on the KPIs proposal. 
We should also decide if we are proposing KPIs or guidance. At the moment my impression is that we are not developing the  KPIs with a metric that will allow to measure the status of the metadata and  their improvement.

**Comment by efucile** [comment]
https://wiswiki.wmo.int/tiki-index.php?page=TT-GISC2019

**Comment by efucile** [comment]
Hello @wmo-im/tt-wismd can someone answer this? Can we have a teleconference in July?

**Comment by kateroberts** [comment]
Hi Enrico,

Apologies, have been away (for work, and then personal leave).   Just back and still catching up on emails – I hadn’t got to your June 10th email.
I agree that thus far, we are leaning more towards guidance.
I think that there are some things* which can be checked for, though it would have to be handled tactfully, because many of those things haven't yet been strongly promoted  (so non-compliance would mostly be due to lack of knowledge, or resourcing).
But giving the GISCS a headsup, and getting the process in place sounds like a good approach.

*Whether records contain station ids as keywords (with theme of 'place'), for instance.
Whether records contain data parameters, as keywords;
Whether the online resource (to the data) provides a resolvable link, and to what.
And there will likely be a few more things to be checked for, as well.

I will set up a doodle poll.

Kate

**Comment by efucile** [comment]
KIPs were not ready to be presented. We'll do at next meeting.
